### ISSUE TITLE
Examples are in mm, should be cm

### ISSUE THREAD

**Issue by TurnerRussell50** [sparkfun/SparkFun_Qwiic_XM125_Arduino_Library#3]
https://forum.sparkfun.com/viewtopic.php?f=68&t=61409 Has the main issue thread/citations and example # details

**Comment by brhoff720** [comment]
Thanks for this report and link to the details. in the forum.  We'll have an engineer take a closer look.

**Comment by edspark** [comment]
This was fixed! The millimeters coming out of the registers were being divided by 10.

**Comment by bakuhatsu** [comment]
Thanks @edspark!  I made changes in the file here: `src/sfeQwiicXM125.cpp`

For each Peak (peaks 0 thought 9) there is a function that looks like this: 
```c++
int32_t QwDevXM125::getDistancePeak0Distance(uint32_t &peak)
{
    size_t readBytes = 0;
    int32_t retVal = _theBus->readRegister16Region(SFE_XM125_DISTANCE_PEAK0_DISTANCE, (uint8_t*)&peak, 4, readBytes);
    peak = __builtin_bswap32(peak);
    peak = peak/10;
    return retVal;
}
```
So I removed the line `peak = peak/10` since this is taking the data in mm and converting to cm.  Since the arduino call returns an int32_t, there is no way to get back to mm unless this line is removed.  

After making the change below, the code functioned very well.  

```c++
int32_t QwDevXM125::getDistancePeak0Distance(uint32_t &peak)
{
    size_t readBytes = 0;
    int32_t retVal = _theBus->readRegister16Region(SFE_XM125_DISTANCE_PEAK0_DISTANCE, (uint8_t*)&peak, 4, readBytes);
    peak = __builtin_bswap32(peak);
    return retVal;
}
```

Make the same change on the following lines for each of the different peaks. 
Lines changed: 377, 386, 395, 404, 413, 422, 431, 440, 449, and 458
